apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: demo
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-d114653a-f13c-4921-96d9-823349bc4194:
      events:
        - push
      repositories:
        - owner: matthewchungcodefresh
          names:
            - MatthewChungGitSource
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/csdp/demo/github-d114653a-f13c-4921-96d9-823349bc4194
        url: https://lrcsdp.support.cf-cd.com
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: autopilot-secret
        key: git_token
