apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: demo
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-d114653a-f13c-4921-96d9-823349bc4194
      eventName: github-d114653a-f13c-4921-96d9-823349bc4194
      eventSourceName: demo
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
  triggers:
    - template:
        name: matthew
        conditions: github-d114653a-f13c-4921-96d9-823349bc4194
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: demo-matthew-
              spec:
                workflowTemplateRef:
                  name: argo-hub.ci-simple.0.0.1
          parameters: []
