apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: mc-multiapp
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-33e6100b-95bf-4760-a4ac-a77b8eabcc2c:
      events:
        - push
      repositories:
        - owner: matthewchungcodefresh
          names:
            - example-multiservice2
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/csdp/mc-multiapp/github-33e6100b-95bf-4760-a4ac-a77b8eabcc2c
        url: https://lrcsdp.support.cf-cd.com
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: autopilot-secret
        key: git_token
