apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: mc-multiapp
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-33e6100b-95bf-4760-a4ac-a77b8eabcc2c
      eventName: github-33e6100b-95bf-4760-a4ac-a77b8eabcc2c
      eventSourceName: mc-multiapp
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
  triggers:
    - template:
        name: ctrlr
        conditions: github-33e6100b-95bf-4760-a4ac-a77b8eabcc2c
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: mc-multiapp-ctrlr-
              spec:
                arguments:
                  parameters:
                    - name: GIT_REPO_URL
                      value: ''
                    - name: IMAGE_NAME
                      value: ''
                    - name: IMAGE_TAG
                      value: latest
                    - name: GIT_REVISION
                      value: main
                    - name: GIT_BRANCH
                      value: main
                    - name: GIT_COMMIT_URL
                      value: ''
                    - name: GIT_COMMIT_MESSAGE
                      value: ''
                    - name: DOCKERFILE
                      value: Dockerfile
                    - name: GIT_TOKEN_SECRET
                      value: github-token
                    - name: CONTEXT
                      value: .
                    - name: REGISTRY_CREDS
                      value: dockerhub-creds
                    - name: DOCKER_CONFIG
                      value: dockerhub-config
                workflowTemplateRef:
                  name: mc-ci-simple
          parameters:
            - dest: spec.arguments.parameters.0.value
              src:
                dependencyName: github-33e6100b-95bf-4760-a4ac-a77b8eabcc2c
                dataTemplate: '{{ .Input.body.repository.clone_url }}'
            - dest: spec.arguments.parameters.1.value
              src:
                dependencyName: github-33e6100b-95bf-4760-a4ac-a77b8eabcc2c
                dataTemplate: docker.io/matthewchungcodefresh/ctrlr
            - dest: spec.arguments.parameters.2.value
              src:
                dependencyName: github-33e6100b-95bf-4760-a4ac-a77b8eabcc2c
                dataTemplate: '{{ trunc 7 .Input.body.after }}'
            - dest: spec.arguments.parameters.3.value
              src:
                dependencyName: github-33e6100b-95bf-4760-a4ac-a77b8eabcc2c
                dataTemplate: '{{ .Input.body.after }}'
            - dest: spec.arguments.parameters.4.value
              src:
                dependencyName: github-33e6100b-95bf-4760-a4ac-a77b8eabcc2c
                dataTemplate: '{{ trimPrefix "refs/heads/" .Input.body.ref }}'
            - dest: spec.arguments.parameters.5.value
              src:
                dependencyName: github-33e6100b-95bf-4760-a4ac-a77b8eabcc2c
                dataTemplate: '{{ .Input.body.head_commit.url }}'
            - dest: spec.arguments.parameters.6.value
              src:
                dependencyName: github-33e6100b-95bf-4760-a4ac-a77b8eabcc2c
                dataTemplate: '{{ .Input.body.head_commit.message }}'
            - dest: spec.arguments.parameters.7.value
              src:
                dependencyName: github-33e6100b-95bf-4760-a4ac-a77b8eabcc2c
                dataTemplate: Dockerfile
            - dest: spec.arguments.parameters.8.value
              src:
                dependencyName: github-33e6100b-95bf-4760-a4ac-a77b8eabcc2c
                dataTemplate: github-token
            - dest: spec.arguments.parameters.9.value
              src:
                dependencyName: github-33e6100b-95bf-4760-a4ac-a77b8eabcc2c
                dataTemplate: ctrlr
            - dest: spec.arguments.parameters.10.value
              src:
                dependencyName: github-33e6100b-95bf-4760-a4ac-a77b8eabcc2c
                dataTemplate: dockerhub-creds
            - dest: spec.arguments.parameters.11.value
              src:
                dependencyName: github-33e6100b-95bf-4760-a4ac-a77b8eabcc2c
                dataTemplate: dockerhub-config
